#!/bin/bash
  
###############################################################
#        Dsub run for FastqToSam for Fastq files over 50GB
#                                       
#                                       - 5/17/2019     
#                                       - Jina Song
###############################################################

## Your sample information ##

sample="[YOUR-SAMPLE]"
readgroup="[YOUR-READGROUP]"
platform="[YOUR-PLATFORM]"

fastq1="[YOUR-FASTQ-1]"
fastq2="[YOUR-FASTQ-2]"
ubam="[YOUR-UBAM]"

## dsub command 

dsub \
    --provider google-v2 \
    --project ${mvp_project} \
    --region ${mvp_region} \
    --min-cores 1 \
    --min-ram 32 \
    --preemptible \
    --boot-disk-size 50 \
    --image ${mvp_fastqtoubam_image} \
    --logging gs://${mvp_bucket}/${sample}/logging \
    --disk-size 500 \
    --input FASTQ_1=${fastq1} \
    --input FASTQ_2=${fastq2} \
    --output UBAM=${ubam} \
    --env RG=${readgroup} \
    --env SM=${sample} \
    --env PL=${platform} \
    --command '/gatk/gatk --java-options "-Xmx32G -Djava.io.tmpdir='pwd'/tmp" FastqToSam -TMP_DIR 'pwd'/tmp -F1 ${FASTQ_1} -F2 ${FASTQ_2} -O ${UBAM} -RG ${RG} -SM ${SM} -PL ${PL} -MAX_RECORDS_IN_RAM 10000000'

