#!/bin/bash
  
###############################################################
#                   Dsub run for FastqToSam
#                                       
#                                       - 4/15/2019     
#                                       - Jina Song
###############################################################

## Your sample information ##

sample="[YOUR-SAMPLE]"
readgroup="[YOUR-READGROUP]"
platform="[YOUR-PLATFORM]"

fastq1="[YOUR-FASTQ-1]"
fastq2="[YOUR-FASTQ-2]"
ubam="[YOUR-UBAM]"

## dsub command 

dsub \
    --provider google-v2 \
    --project ${mvp_project} \
    --region ${mvp_region} \
    --min-cores 1 \
    --min-ram 7.5 \
    --preemptible \
    --boot-disk-size 20 \
    --image ${mvp_fastqtoubam_image} \
    --logging gs://${mvp_bucket}/${sample}/logging \
    --disk-size 200 \
    --input FASTQ_1=${fastq1} \
    --input FASTQ_2=${fastq2} \
    --output UBAM=${ubam} \
    --env RG=${readgroup} \
    --env SM=${sample} \
    --env PL=${platform} \
    --use-private-address \
    --command '/gatk/gatk --java-options "-Xmx8G -Djava.io.tmpdir=bla" FastqToSam -F1 ${FASTQ_1} -F2 ${FASTQ_2} -O ${UBAM} -RG ${RG} -SM ${SM} -PL ${PL}'

